version: '3.9'

services:
  pseudo_api:
    build: .
    image: api-test
    expose:
      - ${PORT}
    depends_on:
      - db
    ports:
      - 8080:${PORT} 
    
  db:
    image: postgres
    expose:
      - 5432
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=prueba
    volumes:
      - postgres_test:/var/lib/postgresql/data
volumes:
  postgres_test: 